### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by cmlaird** [rhcan-atak-developer/Nearby-ATAK-Plugin#1]
Hello,

Can you make this an APK for 5.1, please? I was at the Hackathon and just found this. Thanks!

**Comment by rhcan-atak-developer** [comment]
See https://github.com/rhcan-atak-developer/Nearby-ATAK-Plugin/releases/tag/pre-release%2F0.0.2
This APK will work with ATAK 5.1.0.x and 5.2.0.x

**Comment by cmlaird** [comment]
Thank you!!!
